version: '3.4'

services:
  image:
    image: image
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      -.:/code
      - dbdata:/code/db.sqlite3
volumes:
  dbdata:
