# Generated by Django 5.0.3 on 2024-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('institute_email', models.EmailField(max_length=254)),
                ('joining_year', models.SmallIntegerField()),
                ('leaving_year', models.SmallIntegerField()),
                ('role', models.CharField(choices=[('B.Tech', 'Btech'), ('M.Tech', 'Mtech'), ('Phd', 'Phd')], max_length=16)),
                ('academic_program', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_on', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
