# Generated by Django 5.0.3 on 2024-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='leaving_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
