# Generated by Django 5.0.3 on 2024-03-09 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('student', '0002_alter_student_leaving_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('cancelled', 'CANCELLED')], max_length=16)),
                ('due_date', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DueResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response_mode', models.CharField(choices=[('request cancellation', 'REQUEST_CANCELLATION'), ('portal payment', 'PORTAL_PAYMENT'), ('external payment', 'EXTERNAL_PAYMENT')], max_length=32)),
                ('payment_proof_file', models.URLField(default=None, null=True)),
                ('cancellation_reason', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('on hold', 'ON_HOLD'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], max_length=16)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due.due')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due.dueresponse')),
            ],
        ),
    ]
