# Generated by Django 4.1 on 2024-03-22 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('due', '0002_due_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 22, 18, 27, 13, 60664)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dueresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='razorpaypayments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 22, 18, 27, 36, 317743)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razorpaypayments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
