# Generated by Django 4.1 on 2024-03-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('due', '0003_dueresponse_created_at_dueresponse_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueProofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof_media_url', models.URLField()),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='due.due')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
