# Generated by Django 4.1 on 2024-03-13 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_leaving_year'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStudentsMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('allow_certificate_generation', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
