# Generated by Django 4.1 on 2024-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_departmentstudentsmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='certificate_pdf_template',
            field=models.TextField(default='<html><head><title>certificate</title></head><body>No dues Certificate</body></html>'),
            preserve_default=False,
        ),
    ]
