# Generated by Django 4.1 on 2024-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_certificate_pdf_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='default_payment_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
